version: '3.4'
services:
  rbase:
    image: fdrennan/redditsuite:latest
    restart: "always"
    user: 'root'
    volumes:
      - ./main.R:/home/main.R
      - ./.Renviron:/home/.Renviron
      - ./sql:/home/sql
    command: "/usr/bin/Rscript /home/main.R"
    ports:
      - "8787:8787"
