create table if not exists public.submissions
(
    unique_id             varchar primary key,
    fullname              varchar,
    id                    varchar,
    name                  varchar,
    subreddit_id          varchar,
    author                varchar,
    title                 varchar,
    selftext              varchar,
    subreddit             varchar,
    permalink             varchar,
    domain                varchar,
    url                   varchar,
    thumbnail             varchar,
    num_crossposts        integer,
    subreddit_subscribers integer,
    ups                   integer,
    upvote_ratio          double precision,
    archived              bool,
    author_premium        bool,
    hidden                bool,
    is_original_content   bool,
    is_self               bool,
    over_18               bool,
    visited               bool,
    time_collected_utc    timestamptz
);
