version: '3'
services:
  database:
    image: "postgres:13.1" # most recent version
    restart: always
    ports:
      - '5434:5432'
    expose:
      - '5434'
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data:
